# Generated by Django 3.0.8 on 2020-07-22 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on whiche the element was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('slug_name', models.SlugField(unique=True)),
                ('album_name', models.CharField(max_length=60, verbose_name='album name')),
                ('album_picture', models.ImageField(upload_to='player/albums/', verbose_name='album picture')),
                ('total_songs', models.PositiveSmallIntegerField(verbose_name='total tracks')),
                ('release_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on whiche the element was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('slug_name', models.SlugField(unique=True)),
                ('artist_name', models.CharField(max_length=60, verbose_name='artist name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='last_name')),
                ('picture', models.ImageField(upload_to='player/artists/', verbose_name='Picture of artist')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on whiche the element was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('name', models.CharField(max_length=50, verbose_name='Song name')),
                ('time', models.DurationField(verbose_name='track duration')),
                ('mp3', models.FileField(upload_to='player/tracks', verbose_name='track')),
                ('track_number', models.PositiveSmallIntegerField(verbose_name='No album track')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Album')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Artist'),
        ),
    ]
