# Generated by Django 3.0.8 on 2020-07-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='total_songs',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='total tracks'),
        ),
    ]
